name: demo_unlock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+16

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  terminate_restart: ^1.1.0
  unlock_shorebird_kit:
    path: ../unlock_shorebird_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
